version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    env_file:
      - ./env/mongo.env
  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
    image: newborn-backend
  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - '4173:4173'
    volumes:
      - frontend_node_modules:/app/node_modules/
    env_file:
      - ./env/frontend.env
    depends_on:
      - backend
    image: newborn-frontend
volumes:
  mongodb_data:
    name: newborn-mongodb-data
  frontend_node_modules:
    name: newborn-frontend-node_modules
