version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: frontend-dev
    ports:
      - '3000:5173'
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/vite.config.js:/app/vite.config.js
    image: frontend-dev
  npm:
    build: ./
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
